"""Validate and document the F01 mapping contract; does not approve or publish data."""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path

PACKAGE = Path(__file__).resolve().parents[1]
ROOT = PACKAGE.parents[2]
MANIFEST = PACKAGE / 'ingestion/mappings/acnc-register-v3.json'
EVIDENCE = ROOT / 'docs/acnc-live-pilot-validation.json'
REPORT = ROOT / 'docs/acnc-field-coverage.md'


def load(path):
    return json.loads(Path(path).read_text())


def validate(manifest, schema):
    errors = []
    fields = manifest['fields']
    keys = [f['source_key'] for f in fields]
    duplicates = sorted(k for k, n in Counter(keys).items() if n > 1)
    if duplicates:
        errors.append(f'Duplicate source fields: {duplicates}')
    unknown = sorted(set(schema) - set(keys))
    missing = sorted(set(keys) - set(schema))
    if unknown:
        errors.append(f'Unmapped source columns require review: {unknown}')
    if missing:
        errors.append(f'Expected source columns absent: {missing}')
    canonical = [f['canonical_key'] for f in fields]
    if len(set(canonical)) != len(canonical):
        errors.append('Duplicate canonical keys')
    required = ('meaning', 'canonical_type', 'null_handling', 'cardinality',
                'review_unit', 'attribution', 'suppression', 'fixture_ref')
    for f in fields:
        key = f['source_key']
        if key in schema and schema[key] != f['source_type']:
            errors.append(f'Source type changed: {key}')
        if any(not f.get(k) for k in required):
            errors.append(f'Incomplete mapping: {key}')
        if f.get('transform_rule') not in manifest['rules']:
            errors.append(f'Unknown transformation: {key}')
        public = f['public']
        if not public.get('excluded_reason') and not all(
            public.get(k) for k in ('section', 'label', 'route')
        ):
            errors.append(f'Missing public destination: {key}')
        if not all(f['destination'].get(k) for k in ('schema', 'table', 'column', 'status')):
            errors.append(f'Missing database destination: {key}')
    fingerprint = hashlib.sha256(
        json.dumps(schema, sort_keys=True, separators=(',', ':')).encode()
    ).hexdigest()
    if fingerprint != manifest['schema_sha256']:
        errors.append('Observed schema fingerprint differs from mapping contract')
    return errors


def cell(value):
    return str(value).replace('|', '\\|').replace('\n', ' ')


def render(manifest):
    fields = manifest['fields']
    counts = Counter(f['implementation_status'] for f in fields)
    lines = [
        '# ACNC field coverage', '',
        '<!-- Generated by python3 -m ingestion.field_coverage --write; edit the manifest. -->', '',
        f"Contract: `{manifest['manifest_version']}`. Resource: `{manifest['resource_id']}`.", '',
        'Schema evidence: [pilot qualification](acnc-live-pilot-validation.json).', '',
        '**Mapping coverage is not publication coverage.** This contract accounts for all',
        'observed columns; schema, transformations, selected publication and public rendering are implemented.',
        'Retained-pilot replay and the full release gate remain F05.', '',
        f"Total: **{len(fields)} columns**; " + ', '.join(
            f'**{n} {status}**' for status, n in sorted(counts.items())
        ) + '.', '',
        '## Destination design', '', manifest['destination_design'], '',
        '## Remaining qualification', '',
        *['- ' + gate for gate in manifest['qualification_gates']], '',
        '## Column inventory', '',
        '| Source column (type) | Meaning / public label | Canonical key (type) | Rule | Database destination | Public section | Review unit | Current support |',
        '| --- | --- | --- | --- | --- | --- | --- | --- |'
    ]
    for f in fields:
        d = f['destination']
        target = f"{d['schema']}.{d['table']}.{d['column']}"
        if d['json_path']:
            target += ' → ' + d['json_path']
        target += ' (' + d['status'] + ')'
        values = [f"{f['source_key']} ({f['source_type']})", f['meaning'],
                  f"{f['canonical_key']} ({f['canonical_type']})", f['transform_rule'],
                  target, f['public']['section'], f['review_unit'], f['implementation_status']]
        lines.append('| ' + ' | '.join(cell(v) for v in values) + ' |')
    lines += ['', '## Transformation rules', '']
    lines += [f'- **{name}**: {text}' for name, text in manifest['rules'].items()]
    lines += ['', '## Shared contract', '',
              '- Null, blank and absent values mean unknown/not supplied; they never imply deletion.',
              '- Each public fact retains source/resource, source version, raw key/value, mapping version, observation time and publication event.',
              '- The administrative address is one atomic review/suppression group; flags are individually reviewable facts. Whole-record withdrawal overrides every field.',
              '- Missing mappings, source columns or changed types fail the coverage check. Future schema drift must be reviewed, not silently discarded.',
              '- Internal `_id` is excluded from public organisation facts. Its resource-scoped native identity is private and is not proof of stable identity across releases.',
              '- Complete fixture: `tools/ingestion/python/tests/fixtures/acnc-field-coverage.json`. Every column has an invented value, including fields absent in the pilot.',
              '- Fixture edge cases exercise F02 transformations; unknown formats quarantine records for qualification.',
              '', '## Reused references', '']
    for ref in manifest['upstream_references']:
        url = f"https://github.com/{ref['repository']}/blob/{ref['commit']}/{ref['path']}"
        lines.append(f"- [{ref['repository']}: {ref['path']}]({url}) — {ref['use']}")
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true', help='Regenerate the Markdown coverage table')
    parser.add_argument('--schema', type=Path, help='JSON object mapping observed field names to types')
    args = parser.parse_args()
    manifest = load(MANIFEST)
    schema = load(args.schema) if args.schema else load(EVIDENCE)['qualification']['field_types']
    errors = validate(manifest, schema)
    if errors:
        parser.exit(1, '\n'.join(errors) + '\n')
    report = render(manifest)
    if args.write:
        REPORT.write_text(report)
    elif not REPORT.exists() or REPORT.read_text() != report:
        parser.exit(1, 'Coverage report is stale; run with --write.\n')
    print(f"Accounted for {len(schema)} source columns; 69 organisation columns map to 62 review units.")


if __name__ == '__main__':
    main()
